### ISSUE TITLE
Bug Report: Importing Solar from Python not working

### ISSUE THREAD

**Issue by SimpleBinary** [Solar-language/Solar#16]
@Dandigit Could you test this on Python 3.7.2 on Linux and see whether it is the OS or Python Version.
**Describe the bug**
Python returns an error when importing solar from python.

**To Reproduce**
1. Copy one of the package files into the `src/` directory
2. Run Python Shell from the `src/` directory 
3. Type in `import solar`
4. Type in `import <name>.solr or `import <name>` (They both fail)

**Expected behavior**
I expected python to import the file and allow using functions from it.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version: 3.7.2

**Additional Context**

Here is the error 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\...\...\Documents\GitHub\Solar\src\importer.py", line 57, in exec_module
    with open(self.filename) as f:
  File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\encodings\__init__.py", line 100, in search_function
    level=0)
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\...\...\Documents\GitHub\Solar\src\importer.py", line 57, in exec_module
    with open(self.filename) as f:
  File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\encodings\__init__.py", line 164, in _alias_mbcs
    import encodings.mbcs
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\...\...\Documents\GitHub\Solar\src\importer.py", line 57, in exec_module
    with open(self.filename) as f:
  File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\encodings\__init__.py", line 165, in _alias_mbcs
    return encodings.mbcs.getregentry()
AttributeError: module 'encodings' has no attribute 'mbcs'
```

**Comment by Dandigit** [comment]
@SimpleBinary I do not get this error on Ubuntu + Python 3.6.7.

**Comment by Dandigit** [comment]
@SimpleBinary The error that you have makes it look like your Python standard libraries are corrupted or conflicting. Maybe try reinstalling Python?

**Comment by BonfireScratch** [comment]
@SimpleBinary I don't get this error with Python 3.5.2 either

**Comment by SimpleBinary** [comment]
@Dandigit @BonfireScratch It is working now, something's wierd with 64 bit python but on 32 bit it works great.
